name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build /.devcontainer/Dockerfile --file /.devcontainer/Dockerfile --tag myImage:$(date +%s)
      ##--tag mcr.microsoft.com/devcontainers/base:jammy:$(date +%s)
 ##     run: docker buildx build
      
    - name: install app dependencies
      working-directory: ./app
      run: flutter pub get
      
    - name: Run tests
      working-directory: ./app
      run: flutter test

    - name: Build flutter web
      working-directory: ./app
      run: flutter build web
      
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./app/build/web/
