name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    permissions: 
      contents: write

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      working-directory: ./.devcontainer
      run: docker build . --file Dockerfile 

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.10.0'
        
    - name: install app dependencies
      working-directory: ./demoApp
      run: flutter pub get
      
    - name: Run tests
      working-directory: ./demoApp
      run: flutter test

    - name: Build flutter web
      working-directory: ./demoApp
      run: flutter build web
      
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
      #  github_token: ${{secrets.DOCKER_IMAGE_YML}}
        publish_dir: ./demoApp/build/web/
